site_name: Heracles
nav:
  - Home: index.md
  - About: about.md
  - Getting started: getstarted.md
  - Parameters: parameters.md
  - Cadence Spectre: spectre.md
docs_dir: content
theme:
  name: material